version: '3'

networks:
    laravel:

services:
    app:
        build: .
        user: "1000"
        volumes:
            - .:/var/www/html
        networks:
            - laravel

    nginx:
        image: nginx:stable-alpine
        ports:
          - "${PORT:-80}:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
            - mysql
        networks:
            - laravel

    mysql:
        image: mysql:5.6.48
        tty: true
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_DB_SERVER: mysql
            PMA_USER: root
            PMA_PASSWORD: secret
            restart: always
        ports:
            - "${PMA_PORT:-8081}:80"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

volumes:
    dbdata: {}
